<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dokter_model extends CI_Model
{

    public $table = 'dokter';
    public $id = 'kd_dokter';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kd_dokter,nm_dokter,jns_kelamin,tempat_lahir,tanggal_lahir,alamat,no_telepon,sip,spesialisasi,bagi_hasil');
        $this->datatables->from('dokter');
        //add this line for join
        //$this->datatables->join('table2', 'dokter.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('dokter/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('dokter/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('dokter/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'kd_dokter');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kd_dokter', $q);
	$this->db->or_like('nm_dokter', $q);
	$this->db->or_like('jns_kelamin', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_telepon', $q);
	$this->db->or_like('sip', $q);
	$this->db->or_like('spesialisasi', $q);
	$this->db->or_like('bagi_hasil', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kd_dokter', $q);
	$this->db->or_like('nm_dokter', $q);
	$this->db->or_like('jns_kelamin', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_telepon', $q);
	$this->db->or_like('sip', $q);
	$this->db->or_like('spesialisasi', $q);
	$this->db->or_like('bagi_hasil', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dokter_model.php */
/* Location: ./application/models/Dokter_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-10-22 08:12:26 */
/* http://harviacode.com */