<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pasien_model extends CI_Model
{

    public $table = 'pasien';
    public $id = 'nomor_rm';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('nomor_rm,nm_pasien,no_identitas,jns_kelamin,gol_darah,agama,tempat_lahir,tanggal_lahir,no_telepon,alamat,stts_nikah,pekerjaan,keluarga_status,keluarga_nama,keluarga_telepon,tgl_rekam,kd_petugas');
        $this->datatables->from('pasien');
        //add this line for join
        //$this->datatables->join('table2', 'pasien.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pasien/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('pasien/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('pasien/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'nomor_rm');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('nomor_rm', $q);
	$this->db->or_like('nm_pasien', $q);
	$this->db->or_like('no_identitas', $q);
	$this->db->or_like('jns_kelamin', $q);
	$this->db->or_like('gol_darah', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('no_telepon', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('stts_nikah', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('keluarga_status', $q);
	$this->db->or_like('keluarga_nama', $q);
	$this->db->or_like('keluarga_telepon', $q);
	$this->db->or_like('tgl_rekam', $q);
	$this->db->or_like('kd_petugas', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nomor_rm', $q);
	$this->db->or_like('nm_pasien', $q);
	$this->db->or_like('no_identitas', $q);
	$this->db->or_like('jns_kelamin', $q);
	$this->db->or_like('gol_darah', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('no_telepon', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('stts_nikah', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('keluarga_status', $q);
	$this->db->or_like('keluarga_nama', $q);
	$this->db->or_like('keluarga_telepon', $q);
	$this->db->or_like('tgl_rekam', $q);
	$this->db->or_like('kd_petugas', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pasien_model.php */
/* Location: ./application/models/Pasien_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-10-22 08:12:26 */
/* http://harviacode.com */